services:
  db:
    image: mysql:8.0
    container_name: sistema-reserva-hoteis
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db-hoteis
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d 
    networks:
      - app-db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sistema-reserva-hoteis-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq-network

  redis:
      image: "redis:latest"
      container_name: "redis_cache"
      ports:
        - "6379:6379"
      networks:
        - cache-network

  service-payment:
    image: payment-service
    container_name: service-payment
    depends_on:
      - db
      - rabbitmq
      - service-reservas
    ports:
      - "8083:8083"
    networks:
      - app-db
      - cache-network
      - rabbitmq-network

  service-reservas:
    image: reservas-services 
    container_name: service-reservas
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8082:8082"
    networks:
      - app-db
      - cache-network
      - rabbitmq-network

  service-quartos:
    image: quartos-services
    container_name: service-quartos
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8081:8081"
    networks:
      - app-db
      - cache-network
      - rabbitmq-network

volumes:
  db_data:
  rabbitmq_data:

networks:
  cache-network:
    driver: bridge
  app-db:
    driver: bridge
  rabbitmq-network:
    driver: bridge
  
