# Use uma imagem oficial do Alpine Linux como base
FROM alpine:latest

# Instale o wget para baixar o Ngrok
RUN apk add --no-cache wget unzip

# Baixe e descompacte o Ngrok
RUN wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip && \
    unzip ngrok-stable-linux-amd64.zip && \
    mv ngrok /usr/local/bin/ && \
    rm ngrok-stable-linux-amd64.zip

# Defina o entrypoint do container para o Ngrok
ENTRYPOINT ["ngrok"]
