server:
  port: 8088
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
   gateway:
      discovery:
        locator:
          enabled: true # Habilita o Discovery Locator para roteamento dinâmico
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://server-discover:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expõe todos os endpoints, incluindo o `/gateway/routes`
  endpoint:
    gateway:
      enabled: true # Habilita o endpoint específico do Gateway
