server:
  port: 8088
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
   gateway:
      discovery:
        locator:
          enabled: true # Habilita o Discovery Locator para roteamento dinâmico
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://server-discover:8761/eureka/