spring:
  application:
    name: api-server-discover
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # O servidor não precisa se registrar em si mesmo
    fetch-registry: false       # O servidor não precisa buscar o registro
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30 # Frequência com que o cliente envia o heartbeat (padrão: 30 segundos)
    lease-expiration-duration-in-seconds: 90 # Tempo após o qual a instância é marcada como DOWN se o heartbeat não for recebido (padrão: 90 segundos)

