CREATE DATABASE IF NOT EXISTS `db-quartos`;
CREATE DATABASE IF NOT EXISTS `db-reservas`;
CREATE DATABASE IF NOT EXISTS `db-faturamento`;
CREATE DATABASE IF NOT EXISTS `db-feedback`;
CREATE DATABASE IF NOT EXISTS `db-category`;
CREATE DATABASE IF NOT EXISTS `db-disponibilidade`;



